// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoVbdAiTHgGLqCKjUt2OIsbwF9OS_D8i8',
    appId: '1:29770567067:web:91c6d483c6069028ff253e',
    messagingSenderId: '29770567067',
    projectId: 'swift-mart-5b173',
    authDomain: 'swift-mart-5b173.firebaseapp.com',
    storageBucket: 'swift-mart-5b173.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPR8CCQ7svyWX969HbHMxB29v-4yzM4-A',
    appId: '1:29770567067:android:d92abe0248b1c6beff253e',
    messagingSenderId: '29770567067',
    projectId: 'swift-mart-5b173',
    storageBucket: 'swift-mart-5b173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn9f8qfu_myqMkacor19X761H0lP9HU6k',
    appId: '1:29770567067:ios:09ff608493deae7bff253e',
    messagingSenderId: '29770567067',
    projectId: 'swift-mart-5b173',
    storageBucket: 'swift-mart-5b173.appspot.com',
    iosBundleId: 'com.example.swiftMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn9f8qfu_myqMkacor19X761H0lP9HU6k',
    appId: '1:29770567067:ios:09ff608493deae7bff253e',
    messagingSenderId: '29770567067',
    projectId: 'swift-mart-5b173',
    storageBucket: 'swift-mart-5b173.appspot.com',
    iosBundleId: 'com.example.swiftMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoVbdAiTHgGLqCKjUt2OIsbwF9OS_D8i8',
    appId: '1:29770567067:web:1ec07b17dc92ca2eff253e',
    messagingSenderId: '29770567067',
    projectId: 'swift-mart-5b173',
    authDomain: 'swift-mart-5b173.firebaseapp.com',
    storageBucket: 'swift-mart-5b173.appspot.com',
  );
}
