// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArlUrGxSkwJJ0imvDnqky9QBeqUCAAwvc',
    appId: '1:203446715101:web:282a78ea77046b72655134',
    messagingSenderId: '203446715101',
    projectId: 'swift-mart-9e189',
    authDomain: 'swift-mart-9e189.firebaseapp.com',
    storageBucket: 'swift-mart-9e189.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj7TOsvEfwzn4ZUcZvBS2oMr7rFjlah8w',
    appId: '1:203446715101:android:d38d92b590fbde12655134',
    messagingSenderId: '203446715101',
    projectId: 'swift-mart-9e189',
    storageBucket: 'swift-mart-9e189.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASAImQxSopKQ1wTMiMSstbtbj-5ybdzEg',
    appId: '1:203446715101:ios:e963072fa942b6ba655134',
    messagingSenderId: '203446715101',
    projectId: 'swift-mart-9e189',
    storageBucket: 'swift-mart-9e189.appspot.com',
    iosBundleId: 'com.example.swiftMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASAImQxSopKQ1wTMiMSstbtbj-5ybdzEg',
    appId: '1:203446715101:ios:e963072fa942b6ba655134',
    messagingSenderId: '203446715101',
    projectId: 'swift-mart-9e189',
    storageBucket: 'swift-mart-9e189.appspot.com',
    iosBundleId: 'com.example.swiftMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArlUrGxSkwJJ0imvDnqky9QBeqUCAAwvc',
    appId: '1:203446715101:web:d9a9fac898bb1ec3655134',
    messagingSenderId: '203446715101',
    projectId: 'swift-mart-9e189',
    authDomain: 'swift-mart-9e189.firebaseapp.com',
    storageBucket: 'swift-mart-9e189.appspot.com',
  );
}
